/*jslint indent: 2*/
/*global window: false */

window.TogglOrigins = {
  "agenocrm.com": {"url" : "*://*.agenocrm.com/*", "name": "AgenoCRM"},
  "any.do": {"url": "*://web.any.do/*", "name": "Anydo"},
  "asana.com": {"url": "*://app.asana.com/*", "name": "Asana"},
  "assembla.com": {"url": "*://*.assembla.com/*", "name": "Assembla"},
  "atlassian.com": {"url": "*://*.atlassian.com/*", "name": "Atlassian"},
  "atlassian.net": {"url": "*://*.atlassian.net/*", "name": "Atlassian", "clone": "true"},
  "axosoft.com": {"url": "*://*.axosoft.com/*", "name": "Axosoft"},
  "basecamp.com": {"url": "*://*.basecamp.com/*", "name": "Basecamp"},
  "basecamphq.com": {"url": "*://*.basecamphq.com/*", "name": "BasecampHQ", "clone": "true", "file": "basecamp.js"},
  "bitbucket.org": {"url": "*://*.bitbucket.org/*", "name": "Bitbucket"},
  "bitrix24.com": {"url": "*://*.bitrix24.com/*", "name": "Bitrix24"},
  "breeze.pm": {"url": "*://app.breeze.pm/*", "name": "Breeze"},
  "bugzilla.mozilla.org": {"url": "*://bugzilla.mozilla.org/*", "name": "Bugzilla"},
  "capsulecrm.com": {"url": "*://*.capsulecrm.com/*", "name": "CapsuleCRM"},
  "cloudes.me": {"url": "*://*.cloudes.me/*", "name": "Cloudes.me"},
  "codeable.io": {"url": "*://app.codeable.io/*", "name": "Codeable"},
  "devdocs.io": {"url": "*://devdocs.io/*", "name": "Devdocs.io"},
  "dobambam.com": {"url": "*://*.dobambam.com/*", "name": "Dobambam"},
  "doit.im": {"url": "*://*.doit.im/*", "name": "Doit"},
  "doitim.com": {"url": "*://*.doitim.com/*", "name": "Doit", "clone": "true"},
  "draftin.com": {"url": "*://*.draftin.com/*", "name": "Draftin"},
  "drupal.org": {"url": "*://*.drupal.org/*", "name": "Drupal"},
  "eproject.me": {"url": "*://*.eproject.me/*", "name": "Eproject.me"},
  "esa.io": {"url": "*://*.esa.io/*", "name": "Esa.io"},
  "eventum": {"url": "", "name": "Eventum"},
  "evernote.com": {"url": "*://*.evernote.com/*", "name": "Evernote"},
  "exana.io": {"url": "*://*.exana.io/*", "name": "Phabricator"},
  "fogbugz.com": {"url": "*://*.fogbugz.com/*", "name": "Fogbugz"},
  "freshdesk.com": {"url": "*://*.freshdesk.com/*", "name": "Freshdesk"},
  "getflow.com": {"url": "*://*.getflow.com/*", "name": "Getflow"},
  "gingkoapp.com": {"url": "*://gingkoapp.com/*", "name": "Gingkoapp"},
  "github.com": {"url": "*://*.github.com/*", "name": "Github"},
  "gitlab.com": {"url": "*://*.gitlab.com/*", "name": "Gitlab"},
  "gogs.io": {"url": "*://*.gogs.io/*", "name": "Gogs"},
  "calendar.google.com": {"url": "*://calendar.google.com/*", "name": "Google Calendar"},
  "docs.google.com": {"url": "*://docs.google.com/*", "name": "Google Docs"},
  "inbox.google.com": {"url": "*://inbox.google.com/*", "name": "Google Inbox"},
  "keep.google.com": {"url": "*://keep.google.com/*", "name": "Google Keep"},
  "mail.google.com": {"url": "*://mail.google.com/*", "name": "Google Mail"},
  "gqueues.com": {"url": "*://www.gqueues.com/*", "name": "GQueues"},
  "habitica.com": {"url": "*://habitica.com/*", "name": "Habitica"},
  "helpscout.net": {"url": "*://secure.helpscout.net/*", "name": "Helpscout"},
  "jira.com": {"url": "*://*.jira.com/*", "name": "Jira", "file": "atlassian.js"},
  "bugs.jquery.com": {"url": "*://bugs.jquery.com/*", "name": "Jquery Bugs", "file": "trac.js"},
  "kanbanery.com": {"url": "*://*.kanbanery.com/*", "name": "Kanbanery"},
  "liquidplanner.com": {"url": "*://app.liquidplanner.com/*", "name": "Liquidplanner"},
  "mantishub.com": {"url": "*://*.mantishub.com/*", "name": "Mantishub"},
  "mantishub.io": {"url": "*://*.mantishub.io/*", "name": "Mantishub", "clone" : "true"},
  "minicrm.pl": {"url": "*://*.minicrm.pl/*", "name": "Minicrm", "clone": "true", "file": "agenocrm.js"},
  "myjetbrains.com": {"url": "*://*.myjetbrains.com/*", "name": "Myjetbrains", "file": "youtrack.js"},
  "newsletter2go.com": {"url": "*://*.newsletter2go.com/*", "name": "Newsletter2go"},
  "ongemini.com": {"url": "*://*.ongemini.com/*", "name": "Gemini"},
  "openproject.com": {"url": "*://*.openproject.com/*", "name": "Openproject"},
  "phacility.com": {"url": "*://*.phacility.com/*", "name": "Phabricator"},
  "pivotaltracker.com": {"url": "*://*.pivotaltracker.com/*", "name": "PivotalTracker"},
  "planbox.com": {"url": "*://*.planbox.com/*", "name": "Planbox"},
  "podio.com": {"url": "*://*.podio.com/*", "name": "Podio"},
  "producteev.com": {"url": "*://*.producteev.com/*", "name": "Producteev"},
  "proworkflow.net": {"url": "*://*.proworkflow.net/*", "name": "Proworkflow"},
  "proworkflow2.net": {"url": "*://*.proworkflow2.net/*", "name": "Proworkflow", "clone" : "true"},
  "proworkflow3.net": {"url": "*://*.proworkflow3.net/*", "name": "Proworkflow", "clone" : "true"},
  "proworkflow4.net": {"url": "*://*.proworkflow4.net/*", "name": "Proworkflow", "clone" : "true"},
  "proworkflow5.net": {"url": "*://*.proworkflow5.net/*", "name": "Proworkflow", "clone" : "true"},
  "proworkflow6.net": {"url": "*://*.proworkflow6.net/*", "name": "Proworkflow", "clone" : "true"},
  "redbooth.com": {"url": "*://*.redbooth.com/*", "name": "Redbooth"},
  "redmine.org": {"url": "*://*.redmine.org/*", "name": "Redmine"},
  "rememberthemilk.com": {"url": "*://*.rememberthemilk.com/*", "name": "RememberTheMilk"},
  "rindle.com": {"url": "*://*.rindle.com/*", "name": "Rindle"},
  "salesforce.com": {"url": "*://*.salesforce.com/*", "name": "Salesforce"},
  "force.com": {"url": "*://*.force.com/*", "name": "Salesforce Lightning", "file": "salesforce.js"},
  "calendar.sunrise.am": {"url": "*://calendar.sunrise.am/*", "name": "Sunrise Calendar"},
  "sifterapp.com": {"url": "*://*.sifterapp.com/*", "name": "Sifterapp"},
  "slack.com": {"url": "*://*.slack.com/*", "name": "Slack"},
  "smartboard.cl": {"url": "*://*.smartboard.cl/*", "name": "Smartboard"},
  "sourcelair.com": {"url": "*://www.sourcelair.com/*", "name": "Sourcelair"},
  "sprint.ly": {"url": "*://sprint.ly/*", "name": "Sprintly"},
  "taiga.io": {"url": "*://*.taiga.io/*", "name": "Taiga"},
  "targetprocess.com": {"url": "*://*.targetprocess.com/*", "name": "Targetprocess"},
  "teamweek.com": {"url": "*://*.teamweek.com/*", "name": "Teamweek"},
  "teamwork.com": {"url": "*://*.teamwork.com/*", "name": "Teamwork"},
  "teamworkpm.net": {"url": "*://*.teamworkpm.net/*", "name": "Teamwork", "clone" : "true"},
  "testrail.com": {"url": "*://*.testrail.com/*", "name": "Testrail"},
  "testrail.net": {"url": "*://*.testrail.net/*", "name": "Testrail", "clone" : "true"},
  "ticktick.com": { "url": "*://ticktick.com/*", "name": "TickTick"},
  "todoist.com": {"url": "*://*.todoist.com/app*", "name": "Todoist"},
  "toggl.com": {"url": "*://toggl.com/*", "name": "Toggl", "clone": "true"},
  "www.toggl.com": {"url": "*://*.toggl.com/*", "name": "Toggl", "clone": "true"},
  "toodledo.com": {"url": "*://*.toodledo.com/*", "name": "Toodledo"},
  "tpondemand.com": {"url": "*://*.tpondemand.com/*", "name": "Targetprocess", "clone" : "true"},
  "trac-hacks.org": {"url": "*://trac-hacks.org/*", "name": "Trac"},
  "trac.edgewall.org": {"url": "*://trac.edgewall.org/*", "name": "Trac", "clone" : "true"},
  "trac.wordpress.org": {"url": "*://*.trac.wordpress.org/*", "name": "Trac", "clone" : "true"},
  "trello.com": {"url": "*://*.trello.com/*", "name": "Trello"},
  "unfuddle.com": {"url": "*://*.unfuddle.com/*", "name": "Unfuddle"},
  "visualstudio.com": {"url": "*://*.visualstudio.com/*", "name": "VisualStudio"},
  "waffle.io": {"url": "*://waffle.io/*", "name": "Waffle"},
  "wordpress.com": {"url": "*://wordpress.com/*", "name": "Wordpress"},
  "worksection.com": {"url": "*://*.worksection.com/*", "name": "Worksection"},
  "worksection.eu": {"url": "*://*.worksection.eu/*", "name": "Worksection", "clone" : "true"},
  "worksection.net": {"url": "*://*.worksection.net/*", "name": "Worksection", "clone" : "true"},
  "wrike.com": {"url": "*://*.wrike.com/*", "name": "Wrike"},
  "sherpadesk.com": {"url": "*://*.sherpadesk.com/*", "name": "Sherpadesk"},
  "wunderlist.com": {"url": "*://*.wunderlist.com/*", "name": "Wunderlist"},
  "xero.com": {"url": "*://go.xero.com/*", "name": "Xero"},
  "zendesk.com": {"url": "*://*.zendesk.com/*", "name": "Zendesk"},
  "books.zoho.com": {"url": "*://books.zoho.com/*", "name": "Zoho Books"},
  "zube.io": {"url": "*://zube.io/*", "name": "Zube"}
};
